language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x

env:
  - GO111MODULE=on

install: true

before_script:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/megacheck
  - go get github.com/fzipp/gocyclo

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go vet .
  - megacheck .
  - gocyclo -avg .
  - golint .

after_success: bash <(curl -s https://codecov.io/bash)